### ISSUE TITLE
Verification error during server invitation

### ISSUE THREAD

**Issue by FatmaBinDuwaya** [ZTE2976/Bad-Apple-Discord-bot#2]
Hello, 

When I tried to invite the bot into my server, it had a verification error. 
please check the image attached. 
![image](https://user-images.githubusercontent.com/115420914/194770706-21b760ac-b634-4447-8694-4d490f322a2a.png)

**Comment by ZTE2976** [comment]
It appears that the bot is already in 100 servers and to join more it needs to be verified, I have another one in less than 100 servers  which can be invited with this link: https://discord.com/oauth2/authorize?client_id=860734283576115200&permissions=3193856&scope=bot

**Comment by FatmaBinDuwaya** [comment]
Thank you,
this one got added.

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows
